#!/usr/bin/env bash
# Deliver one user's price alerts (pipeline/price_alerts.py) to their own chat: a Hermes cron job in
# their profile, every 5 min on weekdays 09:00–18:55 VN (covers the 18:00 close_sync retry), runs
# ops/pending_alerts.py with --no-agent — stdout goes verbatim through the profile's own bot, no
# LLM call, nothing sent when there is nothing new. Failures stay in `hermes cron incidents`
# instead of reaching the user.
# Idempotent: an existing job of the same name is left as is. ops/add_user.sh calls this; run it by
# hand once for users added before price alerts existed.
#
# Usage: ops/setup_alerts_cron.sh <tên profile>
set -euo pipefail

HERMES="${HERMES_CONTAINER:-hermes-gateway}"
NAME="${1:-}"
if [[ ! "$NAME" =~ ^[a-z0-9]+$ || "$NAME" == "default" ]]; then
  echo "usage: $0 <tên profile: a-z0-9, không phải default>" >&2
  exit 2
fi
JOB=vn-market-alerts
PROFILE=/opt/data/profiles/$NAME

TG_ID=$(docker exec "$HERMES" /opt/hermes/.venv/bin/python -c "
import yaml; print(yaml.safe_load(open('$PROFILE/config.yaml'))['mcp_servers']['vn-market-mcp']['env']['VNMCP_USER_ID'])")
[[ "$TG_ID" =~ ^[0-9]+$ ]] || { echo "profile $NAME không có VNMCP_USER_ID hợp lệ: '$TG_ID'" >&2; exit 1; }

# Cron scripts must live in the profile's own scripts/ dir; Hermes runs .sh files with bash.
docker exec -u hermes -i "$HERMES" sh -c "mkdir -p $PROFILE/scripts && cat > $PROFILE/scripts/$JOB.sh" <<EOF
# Generated by vn-market-mcp ops/setup_alerts_cron.sh — prints this profile's pending price alerts.
cd /opt/vn-market-mcp && exec /opt/data/vn-market-mcp-venv/bin/python -m ops.pending_alerts --hermes-config $PROFILE/config.yaml
EOF

if docker exec -u hermes "$HERMES" hermes -p "$NAME" cron list --all | grep -q "Name: *$JOB\$"; then
  echo "cron $JOB của $NAME đã có, giữ nguyên"
else
  docker exec -u hermes "$HERMES" hermes -p "$NAME" cron create "*/5 2-11 * * 1-5" \
    --name "$JOB" --script "$JOB.sh" --no-agent \
    --deliver "telegram:$TG_ID" --failure-deliver local
fi
docker exec -u hermes "$HERMES" hermes -p "$NAME" cron list | grep -A4 "Name: *$JOB" || true
